### ISSUE TITLE
Why I couldn't use relative path in home-manager module?

### ISSUE THREAD

**Issue by babygau** [kclejeune/system#110]
Hi, just came across your config from Reddit and I really like your code structure. I'm new about Nix and trying to simplify your config however I got the issue when building your setup. `nix build` complain that _access path is forbidden at... in restricted mode_
I fixed this after doing some research by using `--impure` argument. You can see it in the following link:
https://github.com/babygau/nix/blob/4d2ab96c65f02059d66a4cad4d71d297d045d46e/modules/home-manager/dotfiles.nix
Currently, I have `dotfiles` folder with `nix` inside which is a fork from your config. Atm, I couldn't use sth like `../../../alacritty`. Could you please explain to me?

**Comment by kclejeune** [comment]
> Hi, just came across your config from Reddit and I really like your code structure. I'm new about Nix and trying to simplify your config however I got the issue when building your setup. `nix build` complain that _access path is forbidden at... in restricted mode_
> 
> I fixed this after doing some research by using `--impure` argument. You can see it in the following link:
> 
> https://github.com/babygau/nix/blob/4d2ab96c65f02059d66a4cad4d71d297d045d46e/modules/home-manager/dotfiles.nix
> 
> Currently, I have `dotfiles` folder with `nix` inside which is a fork from your config. Atm, I couldn't use sth like `../../../alacritty`. Could you please explain to me?
> 
> 

Hey, glad this was able to help you get started!

You're getting this issue because you're pointing to an arbitrary file path by interpolating `target = ${config.user.home}/dotfiles/file`. To replicate what I'm doing, you need to use a relative path rather than a string, like `target = ../path/to/file`.

This puts any file that you reference in the nix store and should resolve

**Comment by babygau** [comment]
Thank you for quick response. I tried to do as your suggestion but `nix build` complain

```
/nix/store/hash......-source/alacritty is not file or directory
```

**Comment by kclejeune** [comment]
> Thank you for quick response. I tried to do as your suggestion but `nix build` complain
> 
> ```
> /nix/store/hash......-source/alacritty is not file or directory
> ```

Make sure your git repo is tracking that file, otherwise the flake won't recognize that it exists :)

**Comment by babygau** [comment]
Sorry for asking silly question. What do you mean by it?. Because I have `dotfiles` and `nix` are all git repo, and `nix` is a submodule of `dotfiles`. Was it the reason?

**Comment by kclejeune** [comment]
> Sorry for asking silly question. What do you mean by it?. Because I have `dotfiles` and `nix` are all git repo, and `nix` is a submodule of `dotfiles`. Was it the reason?  

Yep, you should have it the other way around. Your dotfiles should be a sub folder (not submodule) of your nix config so that your nix repo is the single source of truth.

**Comment by babygau** [comment]
Oh, I see. That makes sense to me! I'll restructure my config and let you know if the problem is solved. Many thanks @kclejeune

**Comment by kclejeune** [comment]
> Oh, I see. That makes sense to me! I'll restructure my config and let you know if the problem is solved. Many thanks @kclejeune 

Happy to help! Just close the issue once you've got it working.

**Comment by babygau** [comment]
> > Oh, I see. That makes sense to me! I'll restructure my config and let you know if the problem is solved. Many thanks @kclejeune
> 
> Happy to help! Just close the issue once you've got it working.

@kclejeune, quick update. I successfully built the config thanks to your suggestion. However, I found out later on that `nix` packages defined in `home-manager` is not installed. What could go wrong?. 

```
❯ ./result/sw/bin/darwin-rebuild switch --flake ~/.nixpkgs
warning: Git tree '/Users/babygau/nix' is dirty
building the system configuration...
warning: Git tree '/Users/babygau/nix' is dirty
user defaults...
setting up user launchd services...
Homebrew bundle...
Using beeftornado/rmtree
Using homebrew/bundle
Using homebrew/cask
Using homebrew/cask-fonts
Using homebrew/cask-versions
Using homebrew/core
Using homebrew/services
Using beeftornado/rmtree/brew-rmtree
Using mas
Using hammerspoon
Using iina
Using karabiner-elements
Using keepingyouawake
Using maccy
Using syncthing
Using visual-studio-code-insiders
Using bitwarden
Homebrew Bundle complete! 17 Brewfile dependencies now installed.
setting up groups...
setting up users...
setting up ~/Applications...
applying patches...
setting up /etc...
system defaults...
setting up launchd services...
configuring networking...
configuring fonts...
Activating home-manager configuration for babygau
Starting home manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating copyFonts
Activating installPackages
Activating linkGeneration
Cleaning up orphan links from /Users/babygau
No change so reusing latest profile generation 1
Creating home file links in /Users/babygau
Activating onFilesChange
```

**Comment by kclejeune** [comment]
> > > Oh, I see. That makes sense to me! I'll restructure my config and let you know if the problem is solved. Many thanks @kclejeune
> 
> > 
> 
> > Happy to help! Just close the issue once you've got it working.
> 
> 
> 
> @kclejeune, quick update. I successfully built the config thanks to your suggestion. However, I found out later on that `nix` packages defined in `home-manager` is not installed. What could go wrong?. 
> 
> 
> 
> ```
> 
> ❯ ./result/sw/bin/darwin-rebuild switch --flake ~/.nixpkgs
> 
> warning: Git tree '/Users/babygau/nix' is dirty
> 
> building the system configuration...
> 
> warning: Git tree '/Users/babygau/nix' is dirty
> 
> user defaults...
> 
> setting up user launchd services...
> 
> Homebrew bundle...
> 
> Using beeftornado/rmtree
> 
> Using homebrew/bundle
> 
> Using homebrew/cask
> 
> Using homebrew/cask-fonts
> 
> Using homebrew/cask-versions
> 
> Using homebrew/core
> 
> Using homebrew/services
> 
> Using beeftornado/rmtree/brew-rmtree
> 
> Using mas
> 
> Using hammerspoon
> 
> Using iina
> 
> Using karabiner-elements
> 
> Using keepingyouawake
> 
> Using maccy
> 
> Using syncthing
> 
> Using visual-studio-code-insiders
> 
> Using bitwarden
> 
> Homebrew Bundle complete! 17 Brewfile dependencies now installed.
> 
> setting up groups...
> 
> setting up users...
> 
> setting up ~/Applications...
> 
> applying patches...
> 
> setting up /etc...
> 
> system defaults...
> 
> setting up launchd services...
> 
> configuring networking...
> 
> configuring fonts...
> 
> Activating home-manager configuration for babygau
> 
> Starting home manager activation
> 
> Activating checkFilesChanged
> 
> Activating checkLinkTargets
> 
> Activating writeBoundary
> 
> Activating copyFonts
> 
> Activating installPackages
> 
> Activating linkGeneration
> 
> Cleaning up orphan links from /Users/babygau
> 
> No change so reusing latest profile generation 1
> 
> Creating home file links in /Users/babygau
> 
> Activating onFilesChange
> 
> ```

are you specifying a host? it should be something like

`darwin-rebuild switch --flake ~/nixpkgs#host`

could you also provide the output of 

`which nix` and `nix --version`

**Comment by babygau** [comment]
@kclejeune I did `./result/sw/bin/darwin-rebuild switch --flake ~/.nixpkgs#imac` but it's not working. 

<img width="896" alt="Screen Shot 2021-07-10 at 11 14 39 am" src="https://user-images.githubusercontent.com/1514823/125147653-074cea00-e170-11eb-9001-9f0f61f74af8.png">

**Comment by kclejeune** [comment]
> @kclejeune I did `./result/sw/bin/darwin-rebuild switch --flake ~/.nixpkgs#imac` but it's not working. 
> 
> 
> 
> <img width="896" alt="Screen Shot 2021-07-10 at 11 14 39 am" src="https://user-images.githubusercontent.com/1514823/125147653-074cea00-e170-11eb-9001-9f0f61f74af8.png">
> 
> 
> 
> 

That's the right version of nix?

**Comment by babygau** [comment]
FYI, I used [https://github.com/numtide/nix-unstable-installer](nix-unstable-installer)

**Comment by kclejeune** [comment]
> @kclejeune FYI, I used [nix-unstable-installer](https://github.com/numtide/nix-unstable-installer)
> 
> 
> 
> Updated: I reinstalled `nix` following `install-nix.sh` script but it's not working
> 
> 
> 
> It appears to me when building config, `nix` used `default` username. It should be my username `babygau` right?
> 
> 
> 
> ```
> 
> nix-channel --update
> 
> error: creating symlink from '/Users/babygau/.nix-defexpr/.0_channels' to '/nix/var/nix/profiles/per-user/babygau/channels': Permission denied
> 
> 
> 
> which nix-channel
> 
> /nix/var/nix/profiles/default/bin/nix-channel 
> 
> ```

Nix channels shouldn't matter since this is a flake config. I'm pretty sure you have the correct nix version. Unless you're missing other packages, this looks about right to me.

**Comment by babygau** [comment]
> > @kclejeune FYI, I used [nix-unstable-installer](https://github.com/numtide/nix-unstable-installer)
> > Updated: I reinstalled `nix` following `install-nix.sh` script but it's not working
> > It appears to me when building config, `nix` used `default` username. It should be my username `babygau` right?
> > ```
> > 
> > nix-channel --update
> > 
> > error: creating symlink from '/Users/babygau/.nix-defexpr/.0_channels' to '/nix/var/nix/profiles/per-user/babygau/channels': Permission denied
> > 
> > 
> > 
> > which nix-channel
> > 
> > /nix/var/nix/profiles/default/bin/nix-channel 
> > ```
> 
> Nix channels shouldn't matter since this is a flake config. I'm pretty sure you have the correct nix version. Unless you're missing other packages, this looks about right to me.

@kclejeune thank you for your answer, I know it's too much to ask for but if you got some free time, could you have a look at my config at [babygau/nix](https://github.com/babygau/nix/tree/tdt). Atm, I'm struggling to find out the bug as you mentioned. Hence the main topic issue is solved, I'll close it

**Comment by kclejeune** [comment]
> > Nix channels shouldn't matter since this is a flake config. I'm pretty sure you have the correct nix version. Unless you're missing other packages, this looks about right to me.
> 
> 
> 
> @kclejeune thank you for your answer, I know it's too much to ask for but if you got some free time, could you have a look at my config at [babygau/nix](https://github.com/babygau/nix/tree/tdt). Atm, I'm struggling to find out the bug as you mentioned. Hence the main topic issue is solved, I'll close it

I'm still not totally sure what issue you're having it *looks* like all of the home manager packages (including `nix`) are loading fine - if you can clarify I'm happy to look!

**Comment by babygau** [comment]
@kclejeune Thank you! I eventually found the issue. It's because the terminal loaded my local `~/.zshrc` hence the `PATH` is not correct. 
I copy this line from `/etc/zshenv`

```zsh
if [ -z "$__NIX_DARWIN_SET_ENVIRONMENT_DONE" ]; then
  . /nix/store/9mnc5b2x2c436p12pszgkiif5jvn7ywx-set-environment
fi
```

and put in `.zshrc` and now it worked!

**Comment by kclejeune** [comment]
> @kclejeune Thank you! I eventually found the issue. It's because the terminal loaded my local `~/.zshrc` hence the `PATH` is not correct. 
> 
> I copy this line from `/etc/zshenv`
> 
> 
> 
> ```zsh
> 
> if [ -z "$__NIX_DARWIN_SET_ENVIRONMENT_DONE" ]; then
> 
>   . /nix/store/9mnc5b2x2c436p12pszgkiif5jvn7ywx-set-environment
> 
> fi
> 
> ```
> 
> 
> 
> and put in `.zshrc` and now it worked!

Glad you got it worked out! I would suggest managing this with `programs.zsh` in home manager if you can help it - this line may not work indefinitely since it relies on a specific nix store path.

**Comment by babygau** [comment]
Thank you heaps! I got everything  up and running. Today I learned  `config.lib.file.makeOutOfSymbolLink`. So I can decouple dotfiles from Nix repo. Cheers!

**Comment by kclejeune** [comment]
> Thank you heaps! I got everything  up and running. Today I learned  `config.lib.file.makeOutOfSymbolLink`. So I can decouple dotfiles from Nix repo. Cheers!

If you can help it, I'd still avoid this if you can. Ideally you want to keep your dotfiles in this repo and use `home.file` or `programs.stuff` to manage your configuration. If you want any guidance for this let me know.

**Comment by babygau** [comment]
> If you can help it, I'd still avoid decoupling if you can. Ideally you want to keep your dotfiles in this repo and use `home.file` or `programs.stuff` to manage your configuration. If you want any guidance for this let me know.

I don't know if it's an issue at my side. I used `home.file` and  `xdg.configFile` to keep my dotfiles in sync. However whenever I made changes to those symlinks, my Nvim complain it's read-only mode. That's why I had to use the above solution

Again, I'd really appreciate your time and efforts to help me!

**Comment by kclejeune** [comment]
> > If you can help it, I'd still avoid decoupling if you can. Ideally you want to keep your dotfiles in this repo and use `home.file` or `programs.stuff` to manage your configuration. If you want any guidance for this let me know.
> 
> @kclejeune I don't know if it's an issue at my side. I used `home.file` and  `xdg.configFile` to keep my dotfiles in sync. However whenever I made changes to those symlinks, my Nvim complain it's read-only mode. The workaround is to edit from original then `darwin-rebuild`. That's why I had to go for the above solution
> 
> https://github.com/babygau/nix/blob/12bd6564d230b397614435597b78ce179a98fecb/modules/home-manager/dotfiles.nix
> 

This is because your dotfile symlinks point to nix-store paths that are _copies_ of the dotfiles in your repo. You cannot and should not forcibly edit them directly. 

In this model, you change a dotfile by updating it in your repo and then running a rebuild, which will add a new copy of the file to the nix store, and switch to a new configuration that has a symlink to the modified file. 

This allows you to rollback to your previous dotfiles (via your previous configuration) if something goes bad, and you specifically lose out on this if you continue with your current approach. 

> Ah, I just found out your config is based on multi-user build. Any reason for that?. If I install Nix single user mode, the build fails to complete. Disable nix-daemon doesn't help
> 

Multi-user install is better since it restricts your user from having write access to the nix store. Instead, it generates build users and uses the nix-daemon to assign jobs to them where they can run builds in parallel and write the results in the nix store. 

This preserves immutability, which again, is the core principle that you want to preserve by keeping everything inside this repo in the first place. 

I'm not positive since I don't use the single-user install, but this probably fails because I have options enabled that rely on multiple build users (the `nix.buildCores` or `nix.maxJobs` options are the first things that come to mind as potential issues here). 

> I also noted that, before I was able to use `darwin-rebuild swith --flake .#imac`. Atm, I have to put extra `\` like `darwin-rebuild swith --flake .\#imac`  or else there's an error. Did I do sth wrong with the config?

Which shell are you using? If it's not bash or zsh, maybe try switching to one of them. Alternatively, you might have an option enabled that makes # get used as a comment for inline commands. 

The `.` in `.#hostname` is actually a short URI path that points to your flake (you could point it to `/etc/nixos#host` on a nixos system), so it shouldn't require the trailing backslash. It looks like it's making you escape the `#`.

> 
> Again, I'd really appreciate your time and efforts to help me!
> 
I'm happy to help! Let me know if this works for you, or if anything here doesn't make sense!

**Comment by babygau** [comment]
>  In this model, you change a dotfile by updating it in your repo and then running a rebuild, which will add a new copy of the file to the nix store, and switch to a new configuration that has a symlink to the modified file.

> This allows you to rollback to your previous dotfiles (via your previous configuration) if something goes bad, and you specifically lose out on this if you continue with your current approach.

The point is `dotfiles` is also a `git` repo. I could revert back if anything go wrong. But you're right, it's not a Nix way if I do so.

>  Which shell are you using? If it's not bash or zsh, maybe try switching to one of them. Alternatively, you might have an option enabled that makes # get used as a comment for inline commands.

I'm using zsh, you're right, found out I have interactive comment set by default
